dfx canister call test createCard '(record{data="1"})'
dfx canister call test createCard '(record{data="2"})'
dfx canister call test createCard '(record{data="3"})'
dfx canister call test createCard '(record{data="4"})'
dfx canister call test createCard '(record{data="5"})'
dfx canister call test createCard '(record{data="6"})'